name: todo-app

services:
  postgres:
    container_name: postgres_container
    build:
      context: ./Customs/Postgres
      dockerfile: ./Dockerfile
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -h ${HOST_IP} -p ${POSTGRES_PORT}
      interval: 5s
      timeout: 30s
      retries: 4
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=${POSTGRES_DATA_PATH}
    volumes:
      - type: volume
        source: postgres-volume
        target: ${POSTGRES_DATA_PATH}
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - todo-app-network
    mem_limit: 1g
    mem_reservation: 256m
    mem_swappiness: 1g

  pgbouncer:
    container_name: pgbouncer_container
    build:
      context: ./Customs/Pgbouncer
      dockerfile: ./Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
        required: true
        restart: true
    restart: unless-stopped
    environment:
      - PGBOUNCER_PORT=${PGBOUNCER_PORT}
      - POSTGRESQL_HOST=${HOST_IP}
      - POSTGRESQL_PORT=${POSTGRES_PORT}
      - POSTGRESQL_USERNAME=${POSTGRES_USER}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - PGBOUNCER_DATABASE=${POSTGRES_DATABASE_NAME}
      - PGBOUNCER_AUTH_TYPE=scram-sha-256
      - PGBOUNCER_SERVER_IDLE_TIMEOUT=600
      - PGBOUNCER_POOL_MODE=transaction
      - PGBOUNCER_MAX_CLIENT_CONN=512
      - PGBOUNCER_DEFAULT_POOL_SIZE=128
      - PGBOUNCER_MIN_POOL_SIZE=64
      - PGBOUNCER_RESERVE_POOL_SIZE=32
    ports:
      - ${PGBOUNCER_PORT}:${PGBOUNCER_PORT}
    networks:
      - todo-app-network
    mem_limit: 1g
    mem_reservation: 256m
    mem_swappiness: 1g

volumes:
  postgres-volume:

networks:
  todo-app-network:
    driver: bridge
